name: Sync to Windows Runner

# Trigger this workflow on every push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  sync:
    # 'self-hosted' ensures this job runs on our self-hosted runner instead of GitHub's cloud
    runs-on: self-hosted

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    # Remove unwanted files/directories from the top level of the workspace
    - name: Remove unwanted files and directories
      shell: powershell
      run: |
        # Remove any files or directories starting with .git
        Remove-Item .\.git* -Recurse -Force -ErrorAction SilentlyContinue

        # Remove any files or directories starting with .github
        Remove-Item .\.github* -Recurse -Force -ErrorAction SilentlyContinue

        # Remove any files or directories starting with data
        Remove-Item .\gemini_chat_conversations* -Recurse -Force -ErrorAction SilentlyContinue

        # Remove specific files LICENSE
        Remove-Item .\LICENSE -Force -ErrorAction SilentlyContinue
