name: Sync to Windows Runner

# Trigger this workflow on every push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  sync:
    # 'self-hosted' ensures this job runs on our self-hosted runner instead of GitHub's cloud
    runs-on: self-hosted

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    # (Optional) If you want to run a build script, lint, or do other tasks, add them here
    #- name: Run build or tests (optional)
    #  run: |
    #    echo "Running optional build or test steps here..."
